---
rvm:
  - 2.0.0

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - gem install fog
  - "./script/travis/bundle_install.sh"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - cp .sample.env .env
  - psql -c 'create database "project-name_test";' -U postgres
  - bundle exec rake db:migrate db:test:prepare

after_script:
  - "ruby script/travis/bundle_cache.rb"

bundler_args:
  --without development staging production --path=~/.bundle

script:
  - bundle exec rake spec

notifications:
  campfire:
    rooms:
      thoughtbot:
        - 123abc@123abc
    on_success:
      - always
    on_failure:
      - always
    template:
      - '(%{branch} - %{author}): %{message} - %{build_url}'
